import type { RiskLevel, StatusTone } from "@/lib/types";

const toneMap: Record<string, StatusTone> = {
  healthy: "ok",
  active: "ok",
  completed: "ok",
  passed: "ok",
  approved: "ok",
  allowed: "ok",
  submit_ready: "ok",
  pass: "ok",
  attached: "ok",
  complete: "ok",
  verified: "ok",
  resolved: "ok",
  available: "ok",
  stable: "ok",
  ready: "ok",
  within_window: "ok",
  released_after_evidence: "ok",
  applied_with_expiry: "ok",
  policy_block_preserved: "ok",
  converted_regression_fixture: "ok",
  failed_to_retrying_after_submit: "ok",
  retry_submits_with_audit: "ok",
  cancel_submits_with_audit: "ok",
  low: "ok",
  warning: "warn",
  warning_review: "warn",
  review_required: "warn",
  held_for_second_review: "warn",
  cancelled_state_preserved_pending_review: "warn",
  failed_retry_preserved: "warn",
  cancel_requires_second_review: "warn",
  eval_gate_preserved_by_regression_fixture: "warn",
  expired_requires_release_evidence: "warn",
  dry_run_not_enforced: "warn",
  mixed_preserved: "warn",
  degraded: "warn",
  retrying: "warn",
  review: "warn",
  second_review_required: "warn",
  eval_passed: "warn",
  internal_canary: "warn",
  allowlist_canary: "warn",
  percent_canary: "warn",
  paused: "danger",
  rolled_back: "danger",
  deprecated: "danger",
  draft: "info",
  medium: "warn",
  missing: "warn",
  required: "warn",
  configured: "warn",
  imported: "warn",
  not_retry: "info",
  failed: "danger",
  blocked: "danger",
  blocked_by_policy_or_role: "danger",
  blocked_state_preserved: "danger",
  retry_blocked_until_evidence: "danger",
  hold_blocked_until_policy_review: "danger",
  blocked_not_regression_fixture: "danger",
  blocked_stale_replay: "danger",
  expired: "danger",
  missing_audit: "danger",
  missing_runtime: "danger",
  missing_release_evidence: "danger",
  blocking_denied: "danger",
  exhausted: "danger",
  denied: "danger",
  suspended: "danger",
  critical: "danger",
  high: "danger",
  open: "info",
  pending: "info",
  info: "info"
};

export function StatusBadge({
  value,
  label
}: {
  value: string | RiskLevel;
  label?: string;
}) {
  const tone = toneMap[value] ?? "info";
  return <span className={`badge ${tone}`}>{label ?? value}</span>;
}
